### ISSUE TITLE
Failed mutation in Explorer View

### ISSUE THREAD

**Issue by FloSeu** [starbeachlab/MutationExplorerServer#11]
When a mutation in this view fails, one gets a white PDB without indicated energies and sequence, however the entry and display is still present. No error pops up. When going back to parent and trying a mutation, now an error is generated. The error should be generated the first time a mutation fails and maybe the faulty entry should not be displayed at all.

**Comment by MKampfrath** [comment]
Do you have an example for this? Because I can't reproduce the problem.
