### ISSUE TITLE
job not getting completed

### ISSUE THREAD

**Issue by amitpande74** [starbeachlab/MutationExplorerServer#14]
Dear Author,
The run is 
Status of job 412173:
2024-03-03 13:08:53 Start Calculation
2024-03-03 13:08:53 Start fixbb for mut_0
2024-03-03 13:09:25 fixbb for mut_0 done
forever.
Kindly look into it.

**Comment by amitpande74** [comment]
yet the problem persists
This site can’t be reachedThe webpage at https://proteinformatics.uni-leipzig.de/mutation_explorer/explore/969955/mut_1.pdb might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by dwiegreffe** [comment]
Dear amitpande74,

thank you very much for this report. We had missed the fact that this problem also occurs when using Alignme. We quickly made the necessary corrections and it should now also work with Alignme. We have tested this in this [session](https://proteinformatics.uni-leipzig.de/mutation_explorer/explore/49789/mut_1.pdb) with the data you used.
