### ISSUE TITLE
"invalid chain or residue position"

### ISSUE THREAD

**Issue by DustyFairy** [starbeachlab/MutationExplorerServer#3]
Last week I tried the pdb 7LHY structure where I mutated A:S successfully. When I wanted to try a different mutation I received the error "invalid chain or residue position". I tried different positions and amino acids without any success. 
![image_720](https://github.com/starbeachlab/MutationExplorerServer/assets/33834491/f6620317-3b3d-4c04-8f2e-a49b926d1fef)

**Comment by MKampfrath** [comment]
We have now fixed this problem. However, it is currently not possible to mutate the same residue again. You would have to do the mutation from the parent structure, the 'mut_0' structure.
