### ISSUE TITLE
Tooltip in Explorer View

### ISSUE THREAD

**Issue by FloSeu** [starbeachlab/MutationExplorerServer#8]
On left side in explorer view the window displays "XXXX | Model 1 | Instance 1_555"  <-What is "XXXX"? This should be made more intuitive with its respective meaning.

**Comment by MKampfrath** [comment]
The _XXXX_ is unfortunately added when creating a new pdb. For some reason it does not take the id from the original pdb. I will look into it, thanks.

**Comment by MKampfrath** [comment]
I was told this is a rosetta thing. I will change this up to something different.

**Comment by MKampfrath** [comment]
I fixed it. It now displays the file name instead of XXXX
